### ISSUE TITLE
Issue when scss file includes dashes, not valid pascal case

### ISSUE THREAD

**Issue by weyert** [TeamSupercell/typings-for-css-modules-loader#10]
When you have a file like `_react_date_picker.scss` it generated an invalid TypeScript interface type. The recommended eslint rules for TypeScript enforce pascal case names for types.

**Comment by weyert** [comment]
Hmm, I think the keys are getting from somewhere else e.g. source map or sass itself

**Comment by dannsam** [comment]
Thanks for reporting the issue and sorry that it took too long for me to reply - keep missing GitHub notifications. Going to look at the issue this week unless someone else wants to create a PR.

**Comment by weyert** [comment]
Thank you very much @dannsam 
Appreciated. This PR also gives me a better understanding how everything works :) I will give it a shot when I am back in the office.
