### ISSUE TITLE
Styles defined in bundle.js

### ISSUE THREAD

**Issue by ErikParso** [TeamSupercell/typings-for-css-modules-loader#15]
Hello. I noticed all style definitions is packed in bundle.js and appears in my html as inline styles.
![image](https://user-images.githubusercontent.com/35962203/68753368-33b00c00-0605-11ea-9c4b-cc5c5a1d07a6.png)

Is there a way to receive styles in separated bundle or event better .css files ?

In my webpack config:

```
test: /\.s[ac]ss$/,
use: [
    "style-loader",
    '@teamsupercell/typings-for-css-modules-loader',
    {
        loader: "css-loader",
        options: {
            modules: true,
        }
    },
    "sass-loader"
]
```

**Comment by dannsam** [comment]
Hi Erik, it can be achieved with [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin), please refer to their docs.
