### ISSUE TITLE
Keyframes gets exported as variables

### ISSUE THREAD

**Issue by tabansal** [TeamSupercell/typings-for-css-modules-loader#17]
I have keyframes in scss file, which are used for transition value. When I generate definition for this scss file, the keyframe is also exported as variable. 

Sample code:

```
@keyframes pathAnimation {
    0% {
        stroke-dasharray: 200 0;
        stroke-width: 25;
    }
    99% {
        stroke-dasharray: 0 200;
        stroke-width: 25;
    }
    100% {
        stroke-dasharray: 0 200;
        stroke-width: 0;
    }
}

.shrinkArc {
    stroke-width: 0;
    animation-fill-mode: forwards;
    -webkit-animation-fill-mode: forwards;
    animation: pathAnimation 2s linear;
}
```

Generated definition file has pathAnimation in it.

**Comment by dannsam** [comment]
`css-loader` adds all the keyframes to the generated module. `typings-for-css-modules-loader` just adds `d.ts` files with all the variables from the `css-loader` generated module.
There's an example codesandbox that shows output of a css-loader with keyframes
https://codesandbox.io/s/wandering-field-qyv7e?fontsize=14&hidenavigation=1&theme=dark
