### ISSUE TITLE
Build error for CSS modules with :root only

### ISSUE THREAD

**Issue by jsikorski** [TeamSupercell/typings-for-css-modules-loader#26]
We have encountered an issue with CSS modules that don't contain any "default" classes but include :root pseudo-class. For example for declarations.scss file with the following content:

`:root {
	--background: green;
}`

the build result is:

![image](https://user-images.githubusercontent.com/1140587/82478985-04a5b600-9ad2-11ea-930c-cbc7b08b889e.png)

Adding any "default" class to this file solves the problem.

**Comment by Obi-Dann** [comment]
Publish in version V2.2.1
