### ISSUE TITLE
Getting error on css file

### ISSUE THREAD

**Issue by FBurner** [TeamSupercell/typings-for-css-modules-loader#32]
Getting error using the loader is this a known issue?

CssSyntaxError

(1:1) Unknown word

**Comment by Obi-Dann** [comment]
@FBurner I think there's either an error or in CSS or something isn't right with the configuration. Could you please share your loaders config?

**Comment by this-ren** [comment]
**I encountered the same error.**
`//vue.config.js
// eslint-disable-next-line @typescript-eslint/no-var-requires
const path = require('path')

module.exports = {
  chainWebpack: (config) => {
    config.module
      .rule('styles')
      .test(/\.(c|sc|sa)ss$/)
      .use('@teamsupercell/typings-for-css-modules-loader')
      .loader('@teamsupercell/typings-for-css-modules-loader')
      .options({
        banner:
          '// autogenerated by typings-for-css-modules-loader. \n// Please do not change this file!',
        prettierConfigFile: path.resolve(__dirname, './.prettierrc'),
        verifyOnly: process.env.NODE_ENV === 'production',
      })
      .end()
      .use('css-loader')
      .loader('css-loader')
      .options({
        modules: {
          localIdentName: '[local]_[name]-[hash:base64:10]',
        },
        importLoaders: 2,
        localsConvention: 'camelCase',
      })
  },
  css: {
    requireModuleExtension: false,
    loaderOptions: {
      postcss: {
        plugins: [
          // eslint-disable-next-line @typescript-eslint/no-var-requires
          require('postcss-plugin-px2rem')({
            rootValue: 37.5,
            exclude: /(node_module)/,
            minPixelValue: 3,
          }),
        ],
      },
      scss: {
        prependData: `
                      @import "@/style/gobal.scss";
                  `,
      },
    },
  },
}
`
**The error is as follows:**

>  error  in ./node_modules/normalize.css/normalize.css

Syntax Error: SyntaxError

(1:1) Unknown word

> 1 | // Imports
    | ^
  2 | var ___CSS_LOADER_API_IMPORT___ = require("../css-loader/dist/runtime/api.js");
  3 | exports = ___CSS_LOADER_API_IMPORT___(false);



 @ ./node_modules/normalize.css/normalize.css 4:14-245 15:3-20:5 16:22-253
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.1.101:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

 error  in ./src/views/home/index.scss

Syntax Error: SassError: expected "{".
  ╷
5 │ var ___CSS_LOADER_API_IMPORT___ = require("../../../node_modules/css-loader/dist/runtime/api.js");
  │                                                                                                  ^
  ╵
  /Users/davis/projects/mall-web/src/views/home/index.scss 5:98  root stylesheet


 @ ./src/views/home/index.scss 4:14-382 15:3-20:5 16:22-390
 @ ./src/views/home/index.tsx
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.1.101:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
