### ISSUE TITLE
Upgrading to css-loader@4.2.1 generates properties from a source map

### ISSUE THREAD

**Issue by atomrevival** [TeamSupercell/typings-for-css-modules-loader#33]
After upgrading to css-loader@4.2.1, it seems that I'm generating properties in my `*.d.ts` files from my `*.scss` file AND a source map file. The latter is an assumption due to what comes up in the list, `{ file, mappings, names, sources, sourcesContent, version, ...cssClasses }`.

![extra](https://user-images.githubusercontent.com/5734890/89799987-753afc80-db2e-11ea-9e8c-ba4c56346018.png)

config
```js
{
    test: /\.scss$/,
    use: [
        'style-loader',
        {
            loader: '@teamsupercell/typings-for-css-modules-loader',
            options: {
                banner:
                    '// generated by packages/components/.storybook/main.js\n\n',
            },
        },
        {
            loader: 'css-loader',
            options: {
                modules: {
                    auto: true,
                    exportLocalsConvention: 'camelCaseOnly',
                    localIdentName: '[name]__[local]--[hash:base64:5]',
                },
            },
        },
        {
            loader: 'postcss-loader',
            options: {
                ident: 'postcss',
                plugins: () => [postcssPresetEnv()],
            },
        },
        'sass-loader',
    ],
}
```

**Expected behaviour:**
Only CSS classes from a `.scss` file should be generated as types.

**Comment by Obi-Dann** [comment]
Thanks @atomrevival I'll have a look at this issue shortly

**Comment by shimizacken** [comment]
Seems that the cause of the issue is `content.indexOf("exports.locals")` that always returns `-1`. Changing it into `indexOf(___.locals)` fixing the issue and avoiding getting keys from the sourcemap.

```js
const cssModuleKeys = getCssModuleKeys(
    content.substring(content.indexOf("exports.locals"))
  )
```

Source: 
https://github.com/TeamSupercell/typings-for-css-modules-loader/blob/7a2b2e103ac2b77f20f01706d5571ea3bf57cbcc/src/index.js#L61

**Comment by Obi-Dann** [comment]
Thanks for the investigation @shimizacken! 

I've a PR ready fixing the problem so it should be working with both css-loader 3 and 4. However, I'd have gladly accepted your PR, you don't need a permission to create a PR so please don't hesitate creating a PR next time. 😉 

I am also going to setup a daily build with using both current dependencies from package-lock and latests so hopefully there'll be failing build if the loader stops working with the latest version of css-loader.

**Comment by shimizacken** [comment]
> Thanks for the investigation @shimizacken!
 
My pleasure ☺️ 

> I've a PR ready fixing the problem so it should be working with both css-loader 3 and 4. However, I'd have gladly accepted your PR, you don't need a permission to create a PR so please don't hesitate creating a PR next time. 😉

Thank you!

> I am also going to setup a daily build with using both current dependencies from package-lock and latests so hopefully there'll be failing build if the loader stops working with the latest version of css-loader.

Sound like good approach 👌 

I just tested the latest version and happy to confirm that it is fixed 👍

**Comment by atomrevival** [comment]
Awesome, you guys! Thank you! 👍
