### ISSUE TITLE
Support css-loader v5

### ISSUE THREAD

**Issue by siosphere** [TeamSupercell/typings-for-css-modules-loader#47]
It looks like this no longer functions under css-loader v5. It doesn't produce an error, but no .d.ts file is generated

**Comment by macksal** [comment]
I'm using it with css-loader `^5.0.1` successfully. You should check your setup or share it here.

**Comment by harjis** [comment]
For a while I thought as well that it's not working with v5 but it actually is. My problem was that I run devServer with skaffold in minikube so the .d.ts files were not visible locally 😅

**Comment by jellison** [comment]
v5 is working for me as well. The `style-loader` and `css-loader` options are very finicky. Try using these options:

```
use: [
    {
        loader: 'style-loader',
        options: { esModule: false, modules: { namedExport: true } },
    },
    "@teamsupercell/typings-for-css-modules-loader",
    {
        loader: "css-loader",
        options: { modules: true }
    },
]
```

**Comment by Obi-Dann** [comment]
Just upgraded our project to css-loader 5, everything works fine as well. Going to close this issue
