### ISSUE TITLE
ampersand dash syntax does not produce camel case name

### ISSUE THREAD

**Issue by sushruth** [TeamSupercell/typings-for-css-modules-loader#63]
example syntax from [here](https://github.com/Jimdo/typings-for-css-modules-loader#example)

```scss
.some-class {
  // some styles
  &.someOtherClass {
    // some other styles
  }
  &-sayWhat {
    // more styles
  }
}
```

produces this

```ts
// ...
"someClass-sayWhat": string
// ...
```

which is not camel case.

**Comment by Obi-Dann** [comment]
It all depends on your css-loader configuration. The loader just reads the names from css-loader output. 
Closing the issue because it's not a job of this loader to configure/set the name.
Happy to reopen if css-loader outputs the name in camelCase, but this loader does not detect it
