### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by adriangodong** [TeamSupercell/typings-for-css-modules-loader#7]
Thank you for bringing this package up to the latest version!

While working with this package, I found several issues that can be clarified in the documentation:
* This package no longer replaces `css-loader`, but it has to be added after `css-loader`
* There's mentioned of peer dependency to `css-loader`, but due to the requirement above, this is no longer relevant
* `css-loader` will need to be configured to output CSS Modules (e.g. `options: { modules: true; }`)

**Comment by simPod** [comment]
`modules: true` helped me, thanks!

**Comment by CoericK** [comment]
I'm having issues as well, @adriangodong are you using the latest version for your loaders?
I got the following setup:

**package.json**

```
{
    "@teamsupercell/typings-for-css-modules-loader": "2.0.0",
    "css-loader": "3.2.0",
    "less-loader": "5.0.0",
    "style-loader": "1.0.0",
    "ts-loader": "6.1.0",
    "typescript": "3.6.3",
    "url-loader": "2.1.0",
    "webpack": "4.40.2",
    "webpack-dev-server": "3.8.0"
  }
```
**tsconfig.json**
```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es6",
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "typeRoots": ["node_modules/@types", "./typings"]
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}
```

**webpack.config.js**

```
{
        test: /\.(less)$/,
        use: [
          { loader: 'style-loader' },
          {
            loader: 'css-loader',
            options: { modules: true },
          },
          {
            loader: '@teamsupercell/typings-for-css-modules-loader',
          },
          { loader: 'less-loader', options: { sourceMap: true } },
        ],
}
```
**less/components/logo.less**
```
.logo {
  background-color: red;
  width: 100px;
  height: 100px;
}
```

After running webpack in dev it generates the **logo.d.ts** file that contents:

```
export interface ILogoLess {
    logo: string
}

export const locals: ILogoLess
export default locals
```

I tried importing the styles in several ways but this is the only one that "seems to work":
```
import * as styles from '../../less/component/logo.less' // {logo: "_3_lAqxKX6-Al3YE3MgBx_J"}
```
This works on the DOM, but I get the error:
```
TS2339: Property 'logo' does not exist on type 'typeof import(".../less/component/logo.less")'.
```

I dont know how to fix this, I tried several times now

**Comment by adriangodong** [comment]
@CoericK Swap `css-loader` and `@teamsupercell/typings-for-css-modules-loader` order in the array -- i.e. `style-loader`, `@teamsupercell/typings-for-css-modules-loader`, `css-loader`, and finally `less-loader`.

**Comment by dannsam** [comment]
@adriangodong thanks for reporting the issue and proving the list of things you found missing in the docs. I put them all in the PR, would be keen to get your 👀 on it to ensure I am not missing anything #9

**Comment by bairesdeverick** [comment]
@adriangodong thanks, I changed the order but its not working for me :( can you take a look intohttps://github.com/TeamSupercell/typings-for-css-modules-loader/issues/8?

**Comment by CoericK** [comment]
@adriangodong thanks, I changed the order but its not working for me :( can you please take a look into #8
