### ISSUE TITLE
TS2339: Property does not exist on type 'typeof import ...'

### ISSUE THREAD

**Issue by CoericK** [TeamSupercell/typings-for-css-modules-loader#8]
Thanks for supporting this library, I am facing issues integrating it with less and the latest version for loaders, I tried different setups but only this managed to "work" (kinda)

I got the following setup:

**package.json**

```
{
    "@teamsupercell/typings-for-css-modules-loader": "2.0.0",
    "css-loader": "3.2.0",
    "less-loader": "5.0.0",
    "style-loader": "1.0.0",
    "ts-loader": "6.1.0",
    "typescript": "3.6.3",
    "url-loader": "2.1.0",
    "webpack": "4.40.2",
    "webpack-dev-server": "3.8.0"
  }
```
**tsconfig.json**
```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es6",
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "typeRoots": ["node_modules/@types", "./typings"]
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}
```

**webpack.config.js**

```
{
        test: /\.(less)$/,
        use: [
          { loader: 'style-loader' },
          {
            loader: 'css-loader',
            options: { modules: true },
          },
          {
            loader: '@teamsupercell/typings-for-css-modules-loader',
          },
          { loader: 'less-loader', options: { sourceMap: true } },
        ],
}
```
**less/components/logo.less**
```
.logo {
  background-color: red;
  width: 100px;
  height: 100px;
}
```

After running webpack in dev it generates the **logo.d.ts** file that contents:

```
export interface ILogoLess {
    logo: string
}

export const locals: ILogoLess
export default locals
```

I tried importing the styles in several ways but this is the only one that "seems to work":
```
import * as styles from '../../less/component/logo.less' // {logo: "_3_lAqxKX6-Al3YE3MgBx_J"}
```
This works on the DOM, but I get the error:
```
TS2339: Property 'logo' does not exist on type 'typeof import(".../less/component/logo.less")'.
```

I dont know how to fix this, I tried several times now

_Originally posted by @CoericK in https://github.com/TeamSupercell/typings-for-css-modules-loader/issues/7#issuecomment-531636867_

**Comment by dannsam** [comment]
@CoericK have you tried importing it as a default import? eg.
```ts
import styles from '../../less/component/logo.less'
```
Please let me know if it helps to fix the type checking error, I had to change the generated typings a bit to allow using it with `style-loader` and without (when people import `locals`). 

If using default import works if this case, we might somehow consider getting it working for both default imports and `* as`.

**Comment by CoericK** [comment]
Hey @dannsam thanks for your quick answer, I double checked the order and placed ```@teamsupercell/typings-for-css-modules-loader``` before css loader
Also i tried to use the default method 

```
import styles from '../../less/component/logo.less' // undefined
```

But styles its undefined:

```
index.tsx?07b1:45 Uncaught TypeError: Cannot read property 'logo' of undefined
```

**Comment by dannsam** [comment]
@CoericK out of interested, which loader are you using for TypeScript: `ts-loader`, `awesome-typescript-loader` or `babel-loader`?

**Comment by bairesdeverick** [comment]
As I listed on my dependencies I am using ```ts-loader```

```
{
    "@teamsupercell/typings-for-css-modules-loader": "2.0.0",
    "css-loader": "3.2.0",
    "less-loader": "5.0.0",
    "style-loader": "1.0.0",
    "ts-loader": "6.1.0",
    "typescript": "3.6.3",
    "url-loader": "2.1.0",
    "webpack": "4.40.2",
    "webpack-dev-server": "3.8.0"
  }
```

**Comment by CoericK** [comment]
As I listed on my dependencies I am using ```ts-loader```

```
{
    "@teamsupercell/typings-for-css-modules-loader": "2.0.0",
    "css-loader": "3.2.0",
    "less-loader": "5.0.0",
    "style-loader": "1.0.0",
    "ts-loader": "6.1.0",
    "typescript": "3.6.3",
    "url-loader": "2.1.0",
    "webpack": "4.40.2",
    "webpack-dev-server": "3.8.0"
  }
```

**Comment by CoericK** [comment]
Hey guys, @dannsam any updates regarding my issue?

**Comment by dannsam** [comment]
@CoericK it looks like it's a runtime issue since you change to the default import. I am wondering if your `ts-loader` is configured to use your `tsconfig.json` - My only idea is that `ts-loader` doesn't have a config with `allowSyntheticDefaultImports` set  🤷‍♂

**Comment by ErikParso** [comment]
Hello, I have same problem, but with awesome-typescript-loader.
If i use `import * as styles from './styles.css';` `className={styles.x}` not working due to compilation error.
`className={styles.default.x}` not working either because default is undefined.
default import `import styles from './styles.css'` + `className={styles.x}` not working, again, a default is undefined.

file styles.css.d.ts is generated and looks like this:

```
export interface IStylesCss {
  x: string;
}

export const locals: IStylesCss;
export default locals;
```

in my webpack.config.js i have:

```
test: /\.css$/,
use: [
    'style-loader',
    '@teamsupercell/typings-for-css-modules-loader',
    {
        loader: "css-loader",
        options: {
            modules: true,
        }
    }
]
```

I didn't even configured sass styles yet.

**Comment by dannsam** [comment]
@ErikParso @CoericK started #14 which should resolve this issue. ETA is about 1 or 2 days. Thanks for all the information you provided and for your patience ❤️  
As a workaround, you can try enabling TS compilerOptions `esModuleInterop` to `true`. TypeScript would check whether the module is esModule and either use the value from `default` field or just return the module. I was mistakenly thinking that that behavior is configured by `allowSyntheticDefaultImports` option 😞

**Comment by ErikParso** [comment]
Thanks! esModuleInterop flag with combination of `import styles from './styles.css';` helps. Looking forward to fix.
